### ISSUE TITLE
MySQL에는 다양한 스토리지 엔진이 존재하는데 어떤 스토리지 엔진을 언제 사용하는 것이 좋을까요?

### ISSUE THREAD

**Issue by ghost** [StudyGroup-TEMP/Reading-record#3]

**Comment by ghost** [comment]
저는 아래 사이트가 보기 좋게 정리 되어 있는거 같습니다!
https://nomadlee.com/mysql-%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-%EC%97%94%EC%A7%84-%EC%A2%85%EB%A5%98-%EB%B0%8F-%ED%8A%B9%EC%A7%95/

**Comment by rbsks** [comment]
MyISAM vs InnoDB 비교 자료입니다.
상황에 따라 어떤 스토리지를 써야하는지 정리가 잘 되어있는거 같아서 공유합니다.
https://ledpear.tistory.com/m/57
