### ISSUE TITLE
MVCC를 구현하기 위해서 필요한 InnoDB의 핵심 구성요소는 무엇이며 이를 통해 얻을 수 있는 이점은 무엇이 있을까요?

### ISSUE THREAD

**Issue by ghost** [StudyGroup-TEMP/Reading-record#6]

**Comment by ghost** [comment]
이 핵심구성요소로 생길 수 있는 문제점은 무엇이 있을까요?

**Comment by rbsks** [comment]
핵심요소는 언두 로그 영역이라 생각합니다.
언두 영역의 의해 하나의 레코드가 여러개의 버전을 가지면서 필요에 따라 어느 버전의 데이터를 보여줄지를 결정하기 때문입니다.
또한 잠금 없는 일관된 읽기 기능을 격리 수준에(SERIALIZABLE은 제외) 따라서 버퍼 풀의 데이터를 바로 읽을지 언두 로그 영역에 있는 데이터를 읽을지 결정하게 되는데 READ_UNCOMMITED 격리 수준을 제외한 모든 격리 수준 레벨에서는 언두 로그 영역의 데이터를 읽게 됩니다. 이때 트랙잰션 활성 시간이 길어지게 되면 언두 로그의 데이터를 삭제하지 못 하고 오랫동안 유지하고 있어야 되기 때문에 MySQL 서버가 느려지거나 문제가 발생 할 수 있으니 되도록이면 트랜잭션 활성 시간은 짧게 유지하는 것이 좋습니다.

**Comment by ghost** [comment]
저는 이렇게 생각합니다
